### ISSUE TITLE
Multiple model filtering

### ISSUE THREAD

**Issue by nabobalis** [mpasternak/django-multiseek#10]
I am not sure if this is a feature request or just my lack of understanding about this package.

But I wanted to create a page that would allow me to filter across two or more models.
For example, for table A I want to check one field is true and then reference another (linked) table to make sure another field has a certain value.

**Comment by mpasternak** [comment]
This package can be used to create a database query with graphics.

I've used it for some time and I have a little plan for dividing it into smaller ones and separating the javascript part. Ideally, it could generate queries in a form of DSL language, see my other package ``django-dsl`` . 

From your description I am not sure if you want to query by foreign keys or if you want to perform a sub-query for every row found. The example application which is included contains a list of books by various authors. The main query is performed on the book table, but you can query for authors as well, which is a ForeignKey. 

Let me know if you need any more assistance.

**Comment by nabobalis** [comment]
Ah I see, I think that would work. Thanks!
